### ISSUE TITLE
Immediate internal error: timed out communication with wds sync worker

### ISSUE THREAD

**Issue by Aeolun** [gadget-inc/wds#44]
I'd like to give more info, but this is about all I have:

Running node 16.14.2

```
❯ node_modules/.bin/wds ./src/index.ts
Error: [wds] Internal error: timed out communicating with wds sync worker thread, likely an wds bug
    at SyncWorker.call (/Users/bart.riepe/Projects/horizon-core/node_modules/wds/src/SyncWorker.ts:90:13)
    at compile (/Users/bart.riepe/Projects/horizon-core/node_modules/wds/src/child-process-registration.ts:47:31)
    at Object.require.extensions.<computed> [as .ts] (/Users/bart.riepe/Projects/horizon-core/node_modules/wds/src/child-process-registration.ts:65:32)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by Aeolun** [comment]
@airhorns Sure, here you go.

```
❯ WDS_DEBUG=1 node_modules/.bin/wds ./src/index.ts
[wds pid=4628] starting wds for workspace root /Users/bart.riepe/Projects/horizon-core and workdir /var/folders/ff/mlp019tx2ml271f4q1_g2t_5stkfr0/T/wdst7eUxa
[wds pid=4628] Not loading project config from /Users/bart.riepe/Projects/horizon-core/wds.js, error encountered: ENOENT: no such file or directory, access '/Users/bart.riepe/Projects/horizon-core/wds.js'
[wds pid=4628] Starting supervisor server at /var/folders/ff/mlp019tx2ml271f4q1_g2t_5stkfr0/T/wdst7eUxa/ipc.sock
[wds pid=4628] Started HTTP server on /var/folders/ff/mlp019tx2ml271f4q1_g2t_5stkfr0/T/wdst7eUxa/ipc.sock
[wds pid=4634] syncworker file boot { isMainThread: true, hasWorkerData: false }
[wds pid=4634] booted syncworker worker {
  filename: '/Users/bart.riepe/Projects/horizon-core/node_modules/.pnpm/wds@0.11.0/node_modules/wds/pkg/SyncWorker.js',
  scriptPath: '/Users/bart.riepe/Projects/horizon-core/node_modules/.pnpm/wds@0.11.0/node_modules/wds/pkg/child-process-ipc-worker.js',
  threadId: 1
}
[wds pid=4634] calling syncworker {
  id: 0,
  args: [ '/Users/bart.riepe/Projects/horizon-core/src/index.ts' ],
  sharedBuffer: SharedArrayBuffer {
    [Uint8Contents]: <00 00 00 00 00 00 00 00>,
    byteLength: 8
  }
}
[wds pid=4628] Not loading project config from /Users/bart.riepe/Projects/horizon-core/wds.js, error encountered: ENOENT: no such file or directory, access '/Users/bart.riepe/Projects/horizon-core/wds.js'
[wds pid=4628] searching for filenames {
  config: { ignore: [], extensions: [ '.ts', '.tsx', '.jsx' ] },
  root: '/Users/bart.riepe/Projects/horizon-core',
  globs: [
    '**/*{.tsx,.ts,.jsx,.mjs,.cjs,.js}',
    '!node_modules',
    '!**/*.d.ts'
  ]
}
Error: [wds] Internal error: timed out communicating with wds sync worker thread, likely an wds bug
    at SyncWorker.call (/Users/bart.riepe/Projects/horizon-core/node_modules/.pnpm/wds@0.11.0/node_modules/wds/src/SyncWorker.ts:90:13)
    at compile (/Users/bart.riepe/Projects/horizon-core/node_modules/.pnpm/wds@0.11.0/node_modules/wds/src/child-process-registration.ts:47:31)
    at Object.require.extensions.<computed> [as .ts] (/Users/bart.riepe/Projects/horizon-core/node_modules/.pnpm/wds@0.11.0/node_modules/wds/src/child-process-registration.ts:65:32)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
[wds pid=4628] child process exited with code 1, exiting...
```
